// import dateFormat from "dateformat";

export default function ForgotTemplate(fullname, ip, reset) {
	return `
	<a href=${reset}>Hello ${fullname}, Click here to reset your password of your daily updates account.</a>
	`;
}

/* <!DOCTYPE html>
<html lang="en">
<body>
    <h1>DAILY UPDATES AND VESSEL STATUS</h1>
    <hr>
    <h3>Please Reset your Password</h3>
    <hr>
	<p>Hello <strong>${fullname}</strong>,</p>
	<p>We have sent you this email in response to your request to reset your password.</p>
	<p>To reset your password, follow the link below: </p>
    <a href=${reset}>
            Reset your password
    </a>

	<p>
		<strong><u>Additional Information</u></strong>
	</p>
		<p><strong>IP v4 Address</strong> : ${ip}</p>
		<p><strong>Date</strong> : ${dateFormat(new Date(), "dd-mmm-yyyy")}</p>
		<p><strong>Time</strong> : ${dateFormat(new Date(), "HH:MM:ss")}</p>
    <em>
            If you did not initiate this reset, immediately contact administrator to secure your account.
    </em>
	<hr>
	<p>This mail is generated by the system. Do not reply to this mail. For any assistance Contact <a href="mailto:help@puyvast-dailyupdates.co.in?subject=&amp;body=" target="_blank">Support Team</a></p>
</body>
</html>
	 */
